from __future__ import annotations

from enum import StrEnum


class LoginStatus(StrEnum):
    LOGIN_OK = "LOGIN_OK"
    LOGIN_EXPIRED = "LOGIN_EXPIRED"
    HUMAN_VERIFICATION_REQUIRED = "HUMAN_VERIFICATION_REQUIRED"
    RISK_CONTROL_DETECTED = "RISK_CONTROL_DETECTED"


class RunStatus(StrEnum):
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    PARTIAL_SUCCESS_SAFE_STOP = "PARTIAL_SUCCESS_SAFE_STOP"
    FAILED = "FAILED"
    RECOVERY_MODE = "RECOVERY_MODE"


class NoteStatus(StrEnum):
    OK = "OK"
    NOT_FOUND = "NOT_FOUND"
    NO_LONGER_PUBLIC = "NO_LONGER_PUBLIC"
    ACCESS_RESTRICTED = "ACCESS_RESTRICTED"
    UNKNOWN_UNAVAILABLE = "UNKNOWN_UNAVAILABLE"
    PARSE_PARTIAL = "PARSE_PARTIAL"

